name: calculator
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.8
  connectivity_plus: ^2.1.0
  battery_plus: ^1.0.6
  cupertino_icons: ^1.0.6
  math_expressions: ^2.5.0
  dio: ^5.0.0
  image_picker: ^1.1.2
  connectivity: ^3.0.6 # Note: It's recommended to use connectivity_plus instead.
  battery: ^2.0.3 # Use battery_plus if suitable for your needs.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
